<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FicheFrais extends \App\Entity\FicheFrais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'nbJustificatifs', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'dateModif', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'Etat', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisForfaits', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'visiteur', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisHorsForfaits'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'id', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'nbJustificatifs', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'dateModif', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'Etat', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisForfaits', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'visiteur', '' . "\0" . 'App\\Entity\\FicheFrais' . "\0" . 'ligneFraisHorsForfaits'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FicheFrais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJustificatifs(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJustificatifs', []);

        return parent::getNbJustificatifs();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJustificatifs(?int $nbJustificatifs): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJustificatifs', [$nbJustificatifs]);

        return parent::setNbJustificatifs($nbJustificatifs);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantValide(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantValide', []);

        return parent::getMontantValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantValide(?string $montantValide): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantValide', [$montantValide]);

        return parent::setMontantValide($montantValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', []);

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif(?\DateTimeInterface $dateModif): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', [$dateModif]);

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?\App\Entity\Etat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(?\App\Entity\Etat $Etat): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$Etat]);

        return parent::setEtat($Etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneFraisForfaits(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneFraisForfaits', []);

        return parent::getLigneFraisForfaits();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneFraisForfait(\App\Entity\LigneFraisForfait $ligneFraisForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneFraisForfait', [$ligneFraisForfait]);

        return parent::addLigneFraisForfait($ligneFraisForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneFraisForfait(\App\Entity\LigneFraisForfait $ligneFraisForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneFraisForfait', [$ligneFraisForfait]);

        return parent::removeLigneFraisForfait($ligneFraisForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisiteur(): ?\App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisiteur', []);

        return parent::getVisiteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisiteur(?\App\Entity\Visiteur $visiteur): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisiteur', [$visiteur]);

        return parent::setVisiteur($visiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneFraisHorsForfaits(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneFraisHorsForfaits', []);

        return parent::getLigneFraisHorsForfaits();
    }

    /**
     * {@inheritDoc}
     */
    public function addLigneFraisHorsForfait(\App\Entity\LigneFraisHorsForfait $ligneFraisHorsForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLigneFraisHorsForfait', [$ligneFraisHorsForfait]);

        return parent::addLigneFraisHorsForfait($ligneFraisHorsForfait);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneFraisHorsForfait(\App\Entity\LigneFraisHorsForfait $ligneFraisHorsForfait): \App\Entity\FicheFrais
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneFraisHorsForfait', [$ligneFraisHorsForfait]);

        return parent::removeLigneFraisHorsForfait($ligneFraisHorsForfait);
    }

}
