<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_acceuil' => [[], ['_controller' => 'App\\Controller\\AcceuilController::index'], [], [['text', '/Acceuil']], [], [], []],
    'app_visiteur' => [[], ['_controller' => 'App\\Controller\\VisiteurController::index'], [], [['text', '/Visiteur']], [], [], []],
    'app_visiteur_connecter' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Authentification'], [], [['text', '/Visiteur/Connecter']], [], [], []],
    'app_consulter' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Consulter'], [], [['text', '/Visiteur/Consulter']], [], [], []],
    'app_renseigner' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Renseigner'], [], [['text', '/Visiteur/Renseigner']], [], [], []],
    'app_frais_forfait' => [['id'], ['_controller' => 'App\\Controller\\VisiteurController::Editer'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Visiteur/Renseigner/Editer']], [], [], []],
    'app_initialiser' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Initialiser'], [], [['text', '/Visiteur/Initialiser']], [], [], []],
    'app_espace_visiteur' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Espace'], [], [['text', '/Visiteur/Espace']], [], [], []],
    'app_frais_hors_forfait' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Ajouter'], [], [['text', '/Visiteur/Renseigner/Ajouter']], [], [], []],
    'app_visiteur_deconnexion' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Deconnecter'], [], [['text', '/visiteur/deconnecter']], [], [], []],
    'app_comptable' => [[], ['_controller' => 'App\\Controller\\ComptableController::index'], [], [['text', '/Comptable']], [], [], []],
    'app_comptable_connecter' => [[], ['_controller' => 'App\\Controller\\ComptableController::Authentification'], [], [['text', '/Comptable/Connecter']], [], [], []],
    'app_valider' => [[], ['_controller' => 'App\\Controller\\ComptableController::Valider'], [], [['text', '/Comptable/Valider']], [], [], []],
    'app_actualiser' => [['Visiteur', 'FicheFrais', 'FraisForfait'], ['_controller' => 'App\\Controller\\ComptableController::Actualiser'], ['FicheFrais' => '\\d{2}/\\d{4}'], [['variable', '/', '[^/]++', 'FraisForfait', true], ['variable', '/', '\\d{2}/\\d{4}', 'FicheFrais', true], ['variable', '/', '[^/]++', 'Visiteur', true], ['text', '/Comptable/Valider/Actualiser']], [], [], []],
    'app_reporter' => [['Visiteur', 'FicheFrais', 'FraisHorsForfait'], ['_controller' => 'App\\Controller\\ComptableController::Reporter'], ['FicheFrais' => '\\d{2}/\\d{4}'], [['variable', '/', '[^/]++', 'FraisHorsForfait', true], ['variable', '/', '\\d{2}/\\d{4}', 'FicheFrais', true], ['variable', '/', '[^/]++', 'Visiteur', true], ['text', '/Comptable/Valider/Reporter']], [], [], []],
    'app_validée' => [['Visiteur', 'FicheFrais'], ['_controller' => 'App\\Controller\\ComptableController::Validée'], ['FicheFrais' => '\\d{2}/\\d{4}'], [['variable', '/', '\\d{2}/\\d{4}', 'FicheFrais', true], ['variable', '/', '[^/]++', 'Visiteur', true], ['text', '/Comptable/Valider/Validéé']], [], [], []],
    'app_suivre' => [[], ['_controller' => 'App\\Controller\\ComptableController::Suivre'], [], [['text', '/Comptable/Suivre']], [], [], []],
    'app_espace_comptable' => [[], ['_controller' => 'App\\Controller\\ComptableController::Espace'], [], [['text', '/Comptable/Espace']], [], [], []],
    'app_comptable_deconnexion' => [[], ['_controller' => 'App\\Controller\\ComptableController::Deconnecter'], [], [['text', '/Comptable/deconnecter']], [], [], []],
];
